NAME = sip2smpp

CC  = gcc
CXX = g++

#Link eDitor
LD = $(CC)

#LDFLAGS = -Wall -pedantic -g -O3
LDFLAGS = -Wall -pedantic -g 
ARFLAGS = -pthread -lzdb  -lrt  
#ARFLAGS = -lsmpp34 -pthread -lzdb  -lrt -losip2 
CFLAGS = $(LDFLAGS)
#CXXFLASG = $(LDFLAGS) -std=c++11
CXXFLASG = $(LDFLAGS)
