NAME = sip2smpp

CC  = gcc
CXX = g++

#Link eDitor
LD = $(CC)

#LDFLAGS = -Wall -pedantic -g -O3
#LDFLAGS = -MMD -Wall -pedantic -fPIC -g 
LDFLAGS = -fPIC -Wall -pedantic -g 
ARFLAGS = -pthread -lzdb  -lrt -ldl 
#ARFLAGS = -lsmpp34 -pthread -lzdb  -lrt 
CFLAGS = $(LDFLAGS)
#CXXFLASG = $(LDFLAGS) -std=c++11
CXXFLASG = $(LDFLAGS)
